Repository Team-GBS/GBS-client, pull requests merged in 2023-04, with the labels that each got.

#6 Profile 페이지 퍼블리싱
  src/Utils/Libs/getBookColor.ts
  src/assets/svg/NoneBookIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/atoms/BookListItem/index.tsx
  src/components/Common/atoms/BookListItem/style.ts
  src/components/Common/molecules/BookList/index.tsx
  src/components/Common/molecules/BookList/style.ts
  src/components/Profile/molecules/ProfileModal/index.tsx
  src/components/Profile/molecules/ProfileModal/style.ts
  src/components/Profile/organisms/ProfileTable/index.tsx
  src/components/Profile/organisms/ProfileTable/style.ts
  src/components/Profile/templates/ProfileTable/index.tsx
  src/components/Profile/templates/ProfileTable/style.ts
  src/components/Profile/templates/ProfileTemplate/style.ts
  src/pages/profile.tsx
  src/types/Book.ts
  src/types/Modal.ts
Labels: Type: Publishing

#10 Mainbranch
  package.json
  src/assets/svg/BookIcon.tsx
  src/assets/svg/LeftArrowIcon.tsx
  src/assets/svg/LeftBookIcon.tsx
  src/assets/svg/Mark.tsx
  src/assets/svg/NoMark.tsx
  src/assets/svg/RightArrowIcon.tsx
  src/assets/svg/RightBookIcon.tsx
  src/assets/svg/index.ts
  src/components/Common/organisms/Header/index.tsx
  src/components/Common/organisms/Header/style.ts
  src/components/Main/atoms/BookBox/index.tsx
  src/components/Main/atoms/BookBox/style.ts
  src/components/Main/atoms/state.ts
  src/components/Main/organisms/BookList/index.tsx
  src/components/Main/organisms/BookList/style.ts
  src/components/Main/organisms/BookModal/index.tsx
  src/components/Main/organisms/BookModal/style.ts
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Main/organisms/NewBook/style.ts
  src/components/Main/templates/index.tsx
  src/components/Main/templates/style.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/globals.tsx
  yarn.lock
Labels: Type: Publishing

#12 Feature/commoncomponent
  src/assets/svg/SearchIcon.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Header/style.ts
  src/components/Common/atoms/BookListItem/index.tsx
  src/components/Common/atoms/BookListItem/style.ts
  src/components/Common/molecules/BookList/index.tsx
  src/components/Common/templates/MainTemplates/style.ts
  src/components/Main/organisms/BookList/index.tsx
  src/components/Main/organisms/BookModal/index.tsx
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Main/organisms/NewBook/style.ts
  src/components/Main/templates/index.tsx
  src/components/Main/templates/style.ts
  src/pages/index.tsx
  src/pages/profile.tsx
  src/pages/search.tsx
  src/recoilAtoms/recoilAtomContainer.ts
  src/types/Book.ts
Labels: Type: Simple

#14 New book
  package.json
  src/assets/svg/ApplyIcon.tsx
  src/assets/svg/ProfileIcon.tsx
  src/components/Common/atoms/BookListItem/index.tsx
  src/components/Common/atoms/BookListItem/style.ts
  src/components/Common/organisms/Header/index.tsx
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Main/organisms/NewBook/style.ts
  src/pages/application.tsx
  src/types/Book.ts
  yarn.lock
Labels: Type: Refector, Type: Simple

#15 New book2
  src/components/Common/atoms/BookListItem/style.ts
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Main/organisms/NewBook/style.ts
Labels: Type: Simple

#16 Simple
  src/components/Common/molecules/BookList/index.tsx
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Profile/templates/ProfileTable/index.tsx
Labels: Type: Simple

#17 Book slide
  src/components/Common/atoms/BookListItem/index.tsx
  src/components/Common/atoms/BookListItem/style.ts
  src/components/Main/organisms/NewBook/index.tsx
  src/components/Main/organisms/NewBook/style.ts
Labels: Type: Feature, Type: Simple

#18 fix Modal
  src/components/Common/atoms/BookListItem/index.tsx
  src/components/Main/organisms/BookModal/index.tsx
  src/components/Main/organisms/NewBook/index.tsx
  src/recoilAtoms/recoilAtomContainer.ts
Labels: Type: Simple
